config/routes.rb
Gluedb::Application.routes.draw do

  devise_for :users, :path => "accounts"

  root :to => 'dashboards#index'

  get "dashboards/index"
  get "welcome/index"
  get "tools/premium_calc"
  get "flatuipro_demo/index"

  namespace :admin do
    namespace :settings do
      resources :hbx_policies
    end
    resources :users
  end

  resources :enrollment_addresses

  resources :plan_metrics, :only => :index

  resources :vocab_uploads, :only => [:new, :create]

  resources :enrollment_transmission_updates, :only => :create

  resources(:change_vocabularies, :only => [:new, :create]) do
    collection do
      get 'download'
    end
  end

  resources :edi_transaction_set_payments
  resources :edi_transaction_sets
  resources :edi_transmissions

  resources :enrollments do
    member do
      get :canonical_vocabulary
    end
  end

  resources :application_groups do
    resources :households
    get 'page/:page', :action => :index, :on => :collection
  end
    
  resources :users
  resources :policies

  resources :individuals 
  resources :people do
    get 'page/:page', :action => :index, :on => :collection
    member do
      put :compare
      put :persist_and_transmit
      put :assign_authority_id
    end
  end

  resources :employers do
    get 'page/:page', action: :index, :on => :collection
    member do
      get :group
    end
    resources :employees, except: [:destroy], on: :member do
      member do
        put :compare
        put :terminate
      end
    end
  end

  resources :brokers do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :carriers do
    resources :plans
    get :show_plans
    post :calculate_premium, on: :collection  
  end

  resources :plans, only: [:index, :show] do
    member do
      get :calculate_premium
    end
  end

  resources :policies, only: [:show]

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def new
	  @employer = Employer.find(params[:employer_id])
	  @person = Person.new
    @person.members.build
    @person.addresses.build
    @person.phones.build
    @person.emails.build

    @person.addresses.first.city = "Washington"
    @person.addresses.first.state = "DC"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
	end

	def create
    @person = Person.new(params[:person])
		@employer = Employer.find(params[:employer_id])
    @person.employer = @employer
    @person.updated_by = current_user.email unless current_user.nil?

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @employer, notice: 'Employee was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
	end


  def show
    @person = Person.find(params[:id])
    @employer = Employer.find(params[:employer_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @person }
    end
  end


  def edit
    @person = Person.find(params[:id])
    @employer = Employer.find(params[:employer_id])

    @person.members.build if @person.members.empty?
    @person.addresses.build if @person.addresses.empty?
    @person.phones.build if @person.phones.empty?
    @person.emails.build if @person.emails.empty?
  end


  def update
    @person = Person.find(params[:id])
    @employer = Employer.find(params[:employer_id])
    @person.employer = @employer
    @person.updated_by = current_user.email unless current_user.nil?

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def compare
    @person = Person.find(params[:id])
    @updated_person = Person.new(params[:person])

    # @person.members 
    # assoc_attributes = anything ending with an _id

    admin_attributes = %w[_id created_at deleted_at updated_at updated_by]
    @person_fields = Person.attribute_names.reject { |attrib| admin_attributes.include?(attrib) }
  end


  def terminate

  end


end

app/views/employees/_form.html.erb
<%= f.error_notification %>
  <% if @person.errors.any? %>
  <div class="alert alert-error">
    <h4><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h4>
    <ul>
    <% @person.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.simple_fields_for @employer do |e| %>
  <%= e.input :id, as: :hidden %>
<% end %>

<legend>Name</legend>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
	  <div class="form-inputs">
			<%= render 'people/name_fields', f: f %>

			<%= f.simple_fields_for :members do |member|  %>
				<%= render 'people/member_fields', m: member %>
		  <% end %>
		</div>
	</div>
</div>

<legend>Address</legend>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
	  <div class="form-inputs">
			<%= f.simple_fields_for :addresses do |address|  %>
				<%= render 'people/address_fields', a: address %>
		  <% end %>

			<%#= link_to_add_fields '<i class="icon-plus"></i> Add'.html_safe, f, :addresses, "btn btn-small btn-primary" %>
		</div>
	</div>
</div>
			
<legend>Phone</legend>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
	  <div class="form-inputs">
			<%= f.simple_fields_for :phones do |phone|  %>
				<%= render 'people/phone_fields', p: phone %>
		  <% end %>
			<%#= link_to_add_fields '<i class="icon-plus"></i> Add'.html_safe, f, :phones, "btn btn-small btn-primary" %>
		</div>
	</div>
</div>
			
<legend>Email</legend>
<div class="row">
	<div class="col-md-offset-1 col-md-10">
	  <div class="form-inputs">
			<%= f.simple_fields_for :emails do |email|  %>
				<%= render 'people/email_fields', e: email %>
		  <% end %>
			<%#= link_to_add_fields '<i class="icon-plus"></i> Add'.html_safe, f, :emails, "btn btn-small btn-primary" %>
		</div>
	</div>
</div>

<div class="well well-sm well-default">
  <div class="form-actions">
		<%= f.submit "Create Employee", :class => 'btn btn-primary' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")), people_path, :class => 'btn btn-default' %>
	</div>
</div>

app/views/employees/compare.html.erb
<div class="page-header">
  <ul class="breadcrumb">
  	<% employer = Employer.find(params[:employer_id]) %>
    <li><%= link_to "Employers", employers_path %></li>
    <li><%= link_to employer.name, employer_path(Employer.find(employer.id)) %></li>
    <li class="active">Compare</li>
  </ul>
</div>

<%= simple_form_for(@person, url: employer_employees_path, html: { action: :put, class: 'form-horizontal' }) do |f| %>

	<% @person.fields.each do |pf| %>
		<p><%= "Field: #{pf.humanize}" %></p>
		<p><%= "Before: #{@person[pf]} - After: #{@updated_person[pf]}"
	<% end %>

  <div class="well well-sm well-default">
    <div class="form-actions">
			<%= f.submit "Update Employee", :class => 'btn btn-primary' %>
			<%= link_to t('.cancel', :default => t("helpers.links.cancel")), employer_employee_path(@person), :class => 'btn btn-default' %>
		</div>
	</div>
<% end %>

app/views/employees/edit.html.erb
<div class="page-header">
  <ul class="breadcrumb">
  	<% employer = Employer.find(params[:employer_id]) %>
    <li><%= link_to "Employers", employers_path %></li>
    <li><%= link_to employer.name, employer_path(Employer.find(employer.id)) %></li>
    <li><%= link_to @person.full_name, person_path(@person) %></li>
    <li class="active">Edit</li>
  </ul>
</div>																																								

<%= simple_form_for(@person, url: employer_employees_path, html: { action: :compare, class: 'form-horizontal' }) do |f| %>
	<%= render :partial => 'form', :locals=> {f: f} %>
<% end %>

app/views/employees/new.html.erb
<div class="page-header">
  <ul class="breadcrumb">
  	<% employer = Employer.find(params[:employer_id]) %>
    <li><%= link_to "Employers", employers_path %></li>
    <li><%= link_to employer.name, employer_path(Employer.find(employer.id)) %></li>
    <li class="active">New</li>
  </ul>
</div>

<%= simple_form_for(@person, url: employer_employees_path, html: { action: :post, class: 'form-horizontal' }) do |f| %>
	<%= render :partial => 'form', :locals=> {f: f} %>
<% end %>

app/views/employees/show.html.erb
show.html.erb