config/routes.rb
Gluedb::Application.routes.draw do

  devise_for :users, :path => "accounts"

  root :to => 'dashboards#index'

  get "dashboards/index"
  get "welcome/index"
  get "tools/premium_calc"
  get "flatuipro_demo/index"

  namespace :admin do
    namespace :settings do
      resources :hbx_policies
    end
    resources :users
  end

  resources :enrollment_addresses

  resources :plan_metrics, :only => :index

  resources :vocab_uploads, :only => [:new, :create]

  resources :enrollment_transmission_updates, :only => :create

  resources(:change_vocabularies, :only => [:new, :create]) do
    collection do
      get 'download'
    end
  end

  resources :edi_transaction_set_payments
  resources :edi_transaction_sets
  resources :edi_transmissions

  resources :enrollments do
    member do
      get :canonical_vocabulary
    end
  end

  resources :application_groups do
    resources :households
    get 'page/:page', :action => :index, :on => :collection
  end
    
  resources :users
  resources :policies

  resources :individuals 
  resources :people do
    get 'page/:page', :action => :index, :on => :collection
    member do
      put :compare
      put :persist_and_transmit
      put :assign_authority_id
    end
  end

  resources :employers do
    get 'page/:page', action: :index, :on => :collection
    member do
      get :group
    end
    resources :employees, except: [:destroy], on: :member do
      member do
        put :compare
        put :terminate
      end
    end
  end

  resources :brokers do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :carriers do
    resources :plans
    get :show_plans
    post :calculate_premium, on: :collection  
  end

  resources :plans, only: [:index, :show] do
    member do
      get :calculate_premium
    end
  end

  resources :policies, only: [:show]

end

app/models/parsers/xml/enrollment/enrollee.rb
module Parsers::Xml::Enrollment
  class Enrollee
    def initialize(parser)
      @parser = parser
      @coverage = @parser.at_xpath('./ins:coverage', NAMESPACES)
    end

    def birth_date
      text_date = @parser.at_xpath('./ins:DOB', NAMESPACES).text
      Date.parse(text_date)
    end

    def benefit_begin_date
      Date.parse(@coverage.at_xpath('./ins:benefit_begin_date', NAMESPACES).text)
    end

    def rate_period_date
      raise NotImplementedError
    end

    def premium_amount
      @coverage.at_xpath('./ins:premium_amount', NAMESPACES).text.to_f
    end

    def premium_amount=(amt)
      node = @coverage.at_xpath('./ins:premium_amount', NAMESPACES)
      node.content = amt
    end

    def first_name
      @parser.at_xpath('./con:person/con:name_first', NAMESPACES).text
    end

    def last_name
      @parser.at_xpath('./con:person/con:name_last', NAMESPACES).text
    end

    def name
      [first_name, last_name].join(' ')
    end

    def age
      Ager.new(birth_date).age_as_of(benefit_begin_date)
    end
  end
end

app/models/parsers/xml/enrollment/enrollment_group.rb
module Parsers::Xml::Enrollment
  class EnrollmentGroup
    def initialize(parser)
      @parser = parser
      @plan = @parser.at_xpath('./ins:plan', NAMESPACES)
    end
    
    def hios_plan_id
      @plan.at_xpath('./pln:plan/pln:hios_plan_id', NAMESPACES).text
    end
    
    def premium_amount_total
      @plan.at_xpath('./ins:premium_amount_total', NAMESPACES).text.to_f
    end

    def premium_amount_total=(total)
      node = @plan.at_xpath('./ins:premium_amount_total', NAMESPACES)
      node.content = total
    end
    
    def enrollees
      enrollees = @parser.xpath('./ins:subscriber | ./ins:member', NAMESPACES)
      enrollees.collect { |e| Enrollee.new(e) }
    end

    def aptc
      @plan.at_xpath('./ins:aptc_amount').text.to_f
    end

    def credit
      raise NotImplementedError
    end

    def total_responsible_amount
      @plan.at_xpath('./ins:total_responsible_amount', NAMESPACES).text.to_f
    end

    def total_responsible_amount=(responsible_amount)
      node = @plan.at_xpath('./ins:total_responsible_amount', NAMESPACES)
      node.content = responsible_amount
    end

    def enrollee_premium_sum
      sum = 0
      enrollees.each { |e| sum += e.premium_amount}
      sum
    end
  end
end

app/models/parsers/xml/enrollment/enrollment_group_factory.rb
module Parsers::Xml::Enrollment
  class EnrollmentGroupFactory
    def self.from_xml(doc)
      payload = doc.at_xpath('/proc:Operation/proc:payload', NAMESPACES)
      type = payload.first_element_child.name

      case type
      when 'individual_market_enrollment_group'
        IndividualEnrollmentGroup.new(payload.at_xpath('./ins:individual_market_enrollment_group', NAMESPACES))
      when 'shop_market_enrollment_group'
        ShopEnrollmentGroup.new(payload.at_xpath('./ins:shop_market_enrollment_group', NAMESPACES))
      end
    end
  end
end

app/models/parsers/xml/enrollment/individual_enrollee.rb
module Parsers::Xml::Enrollment
  class IndividualEnrollee < Enrollee
    def rate_period_date
      benefit_begin_date
    end
  end
end

app/models/parsers/xml/enrollment/individual_enrollment_group.rb
module Parsers::Xml::Enrollment
  class IndividualEnrollmentGroup < EnrollmentGroup
    def credit
      @plan.at_xpath('./ins:aptc_amount', NAMESPACES).text.to_f
    end
    
    def enrollees
      enrollees = @parser.xpath('./ins:subscriber | ./ins:member', NAMESPACES)
      enrollees.collect { |e| IndividualEnrollee.new(e) }
    end
  end
end

app/models/parsers/xml/enrollment/namespaces.rb
module Parsers::Xml::Enrollment
  NAMESPACES = {
    proc: 'http://dchealthlink.com/vocabularies/1/process',
    ins: 'http://dchealthlink.com/vocabularies/1/insured',
    con: 'http://dchealthlink.com/vocabularies/1/contact',
    pln: 'http://dchealthlink.com/vocabularies/1/plan',
    emp: 'http://dchealthlink.com/vocabularies/1/employer'
  }
end

app/models/parsers/xml/enrollment/shop_enrollee.rb
module Parsers::Xml::Enrollment 
  class ShopEnrollee < Enrollee
    def initialize(parser, employer)
      @employer = employer
      super(parser)
    end

    def rate_period_date
      @employer.open_enrollment_start
    end
  end
end

app/models/parsers/xml/enrollment/shop_enrollment_group.rb
module Parsers::Xml::Enrollment
  class ShopEnrollmentGroup < EnrollmentGroup
    def credit
      @plan.at_xpath('./ins:total_employer_responsibility_amount', NAMESPACES).text.to_f
    end

    def enrollees
      enrollees = @parser.xpath('./ins:subscriber | ./ins:member', NAMESPACES)
      enrollees.collect { |e| ShopEnrollee.new(e, self.employer) }
    end

    def employer
      fein = @parser.xpath('./emp:employer/emp:fein').text
      Employer.find_for_fein(fein)
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
  end

  def show
    @enrollment = Enrollment.find(params[:id])
  end

  def canonical_vocabulary 
    @enrollment = Policy.find(params[:id])
    generated_filename = "#{@enrollment._id}.xml"
    send_data(@enrollment.to_cv, :type => "application/xml", :disposition => "attachment", :filename => generated_filename)
  end

    def new
    @enrollment = Enrollment.new
    @enrollment.enrollment_members.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enrollment }
    end
  end

  def edit
    @enrollment = Enrollment.find(params[:id])
    @enrollment_members = @enrollment.enrollment_members
  end


  def update
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      if @enrollment.update_attributes(params[:enrollment])
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/views/enrollments/_enrollment_member_fields.html.erb
<fieldset>
	<div class="row">
	  <div class="col-sm-12">
		<%= f.input :hbx_member_id, placeholder: "HBX Member ID" %>
	  </div>
	  <div class="col-sm-12">
		<%= f.input :carrier_member_id, placeholder: "Carrier Member ID" %>
	  </div>
	  <div class="col-sm-12">
		<%= f.input :carrier_policy_id, placeholder: "Carrier Policy ID" %>
	  </div>
	  <div class="col-sm-12">
		<%= f.input :premium_amount, placeholder: "Premium Amount" %>
	  </div>
	  <div class="col-sm-4">
		<%= f.input :coverage_start, as: :string, input_html: {class: 'date_picker'} %>
	  </div>
	  <div class="col-sm-4">
		<%= f.input :coverage_end, as: :string, input_html: {class: 'date_picker'} %>
	  </div>
	</div>
</fieldset>

app/views/enrollments/_form.html.erb
<%= simple_form_for @enrollment, :html => { :class => 'form-horizontal' } do |f| %>

<fieldset>
<div class="row">
  <div class="col-sm-12">
    <%= f.input :hbx_policy_id, placeholder: "HBX Policy ID" %>
  </div>
  <div class="col-sm-12">
    <%= f.input :preceding_enrollment_id, placeholder: "Preceeding Enrollment ID"  %>
  </div>
  <div class="col-sm-3">
    <%= f.input :elected_aptc, as: :decimal, label: "Elected APTC", placeholder: "Elected APTC"  %>
  </div>
  <div class="col-sm-3">
   <%= f.input :applied_aptc, as: :decimal, label: "Applied APTC", placeholder: "Applied APTC"  %>
 </div>
  <div class="col-sm-12">
   <%= f.input :carrier_to_bill, as: :boolean, placeholder: "Carrier to Bill?"  %>
  </div>
  <div class="col-sm-12">
   <%= f.input :pre_amt_tot, as: :decimal, placeholder: "Premium Amount"  %>
  </div>
  <div class="col-sm-12">
    <%= f.input :tot_emp_res_amt, as: :decimal, placeholder: "Total Employer Responsible Amount"  %>
  </div>
  <div class="col-sm-12">
    <%= f.input :tot_res_amt, as: :decimal, placeholder: "Total Responsible Amount"  %>
  </div>
  <div class="col-sm-12">
   <%= f.input :sep_reason, placeholder: "Special Enrollment Period Reason"  %>
  </div>
  <div class="col-sm-12">
    <%= f.input :rs_time, as: :string %>
  </div>
</fieldset>

  <legend>Enrollment Members</legend>
  <%= f.simple_fields_for :enrollment_members do |em|  %>
    <%= render 'enrollment_member_fields', f: em %>
  <% end %>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                enrollments_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<%- model_class = Enrollment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/enrollments/index.html.erb
<%- model_class = Enrollment -%>
<%t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<div class="page-header">
  <%= render 'shared/breadcrumb', crumbs: ['Enrollments'] %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:version) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
      <th><%= model_class.human_attribute_name(:carrier_id) %></th>
      <th><%= model_class.human_attribute_name(:hios_plan_id) %></th>
      <th><%= model_class.human_attribute_name(:coverage_type) %></th>
      <th><%= model_class.human_attribute_name(:bgn_date) %></th>
      <th><%= model_class.human_attribute_name(:e_aptc) %></th>
      <th><%= model_class.human_attribute_name(:aptc) %></th>
      <th><%= model_class.human_attribute_name(:pre_amt_tot) %></th>
      <th><%= model_class.human_attribute_name(:tot_res_amt) %></th>
      <th><%= model_class.human_attribute_name(:tot_emp_res_amt) %></th>
      <th><%= model_class.human_attribute_name(:sep_reason) %></th>
      <th><%= model_class.human_attribute_name(:enrollment_group_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= link_to enrollment.id, enrollment_path(enrollment) %></td>
        <td><%= enrollment.version %></td>
        <td><%= enrollment.deleted_at %></td>
        <td><%= enrollment.carrier_id %></td>
        <td><%= enrollment.hios_plan_id %></td>
        <td><%= enrollment.coverage_type %></td>
        <td><%= enrollment.bgn_date %></td>
        <td><%= enrollment.e_aptc %></td>
        <td><%= enrollment.aptc %></td>
        <td><%= enrollment.pre_amt_tot %></td>
        <td><%= enrollment.tot_res_amt %></td>
        <td><%= enrollment.tot_emp_res_amt %></td>
        <td><%= enrollment.sep_reason %></td>
        <td><%= enrollment.enrollment_group_id %></td>
        <td><%=l enrollment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_enrollment_path(enrollment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      enrollment_path(enrollment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_enrollment_path,
            :class => 'btn btn-primary' %>

app/views/enrollments/new.html.erb
<%- model_class = Enrollment -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/enrollments/show.html.erb
<%- model_class = Enrollment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:version) %>:</strong></dt>
  <dd><%= @enrollment.version %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deleted_at) %>:</strong></dt>
  <dd><%= @enrollment.deleted_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carrier_id) %>:</strong></dt>
  <dd><%= @enrollment.carrier_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hios_plan_id) %>:</strong></dt>
  <dd><%= @enrollment.hios_plan_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coverage_type) %>:</strong></dt>
  <dd><%= @enrollment.coverage_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:e_aptc) %>:</strong></dt>
  <dd><%= @enrollment.e_aptc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:applied_aptc) %>:</strong></dt>
  <dd><%= @enrollment.applied_aptc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_amt_tot) %>:</strong></dt>
  <dd><%= @enrollment.pre_amt_tot %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tot_res_amt) %>:</strong></dt>
  <dd><%= @enrollment.tot_res_amt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tot_emp_res_amt) %>:</strong></dt>
  <dd><%= @enrollment.tot_emp_res_amt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sep_reason) %>:</strong></dt>
  <dd><%= @enrollment.sep_reason %></dd>
  <dt><strong><%= model_class.human_attribute_name(:enrollment_group_id) %>:</strong></dt>
  <dd><%= @enrollment.enrollment_group_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              enrollments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_enrollment_path(@enrollment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              enrollment_path(@enrollment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>