config/routes.rb
Gluedb::Application.routes.draw do

  devise_for :users, :path => "accounts"

  root :to => 'dashboards#index'

  get "dashboards/index"
  get "welcome/index"
  get "tools/premium_calc"
  get "flatuipro_demo/index"

  namespace :admin do
    namespace :settings do
      resources :hbx_policies
    end
    resources :users
  end

  resources :enrollment_addresses

  resources :plan_metrics, :only => :index

  resources :vocab_uploads, :only => [:new, :create]

  resources :enrollment_transmission_updates, :only => :create

  resources(:change_vocabularies, :only => [:new, :create]) do
    collection do
      get 'download'
    end
  end

  resources :edi_transaction_set_payments
  resources :edi_transaction_sets
  resources :edi_transmissions

  resources :enrollments do
    member do
      get :canonical_vocabulary
    end
  end

  resources :application_groups do
    resources :households
    get 'page/:page', :action => :index, :on => :collection
  end
    
  resources :users
  resources :policies

  resources :individuals 
  resources :people do
    get 'page/:page', :action => :index, :on => :collection
    member do
      put :compare
      put :persist_and_transmit
      put :assign_authority_id
    end
  end

  resources :employers do
    get 'page/:page', action: :index, :on => :collection
    member do
      get :group
    end
    resources :employees, except: [:destroy], on: :member do
      member do
        put :compare
        put :terminate
      end
    end
  end

  resources :brokers do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :carriers do
    resources :plans
    get :show_plans
    post :calculate_premium, on: :collection  
  end

  resources :plans, only: [:index, :show] do
    member do
      get :calculate_premium
    end
  end

  resources :policies, only: [:show]

end

app/models/plan.rb
class Plan
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  
  extend Mongorder

  field :name, type: String
  field :abbrev, as: :abbreviation, type: String
  field :hbx_plan_id, type: String  # internal ID for plan
  field :hios_plan_id, type: String
  field :coverage_type, type: String
  field :metal_level, type: String
  field :market_type, type: String 
  field :ehb, as: :ehb_max_as_percent, type: BigDecimal, default: 0.0

  index({ hbx_plan_id: 1 }, { unique: true, name: "exchange_plan_id_index" })
	index({ hios_plan_id: 1 }, { unique: false, name: "hios_plan_id_index" })
  index({ coverage_type: 1 })
  index({ metal_level: 1 })
  index({ market_type: 1 })

  validates_inclusion_of :coverage_type, in: ["health", "dental"]
#  validates_inclusion_of :market_type, in: ["individual", "shop"]


	belongs_to :carrier, index: true
  has_many :policies, :inverse_of => :plan
  has_and_belongs_to_many :employers
  embeds_many :premium_tables

  before_save :invalidate_find_cache

  default_scope order_by(name: 1)

  def invalidate_find_cache
    Rails.cache.delete("Plan/find/hios_plan_id.#{self.hios_plan_id}")
    true
  end

  def self.find_by_hios_id(h_id)
    Rails.cache.fetch("Plan/find/hios_plan_id.#{h_id}") do
      Plan.where(
        :hios_plan_id => h_id
      ).first
    end
  end

  # Provide premium rate given the rate schedule, date coverage will start, and applicant age when coverage starts
  def rate(rate_period_date, benefit_begin_date, birth_date)
    age = Ager.new(birth_date).age_as_of(benefit_begin_date)
    premiums = Collections::Premiums.new(self.premium_tables).for_date(rate_period_date).for_age(age)
    premiums.to_a.first
  end

  def premium_for_enrollee(enrollee)
    rate(enrollee.rate_period_date, enrollee.benefit_begin_date, enrollee.birth_date) 
  end

  def self.default_search_order
    [
      ["name", 1],
    ]
  end

  def self.search_hash(s_str)
    search_rex = Regexp.compile(Regexp.escape(s_str), true)
    {
      "$or" => [
        {"name" => search_rex}
      ]
    }
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @q = params[:q]
    @qf = params[:qf]
    @qd = params[:qd]

    if params[:q].present?
      @plans = Plan.search(@q, @qf, @qd).page(params[:page]).per(15)
    else
      @plans = Plan.page(params[:page]).per(15)
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def calculate_premium
    plan = Plan.find(params[:id])
    rate_period_date = extract_date(params[:rate_period_date])
    benefit_begin_date = extract_date(params[:benefit_begin_date])
    birth_date = extract_date(params[:birth_date])

    @rate = plan.rate(rate_period_date, benefit_begin_date, birth_date)
    
    respond_to do |format|
      format.js
    end
  end

  private
  
  def extract_date(raw_date)
    DateTime.strptime(raw_date, '%m/%d/%Y')
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_plan_search.html.erb
<%= form_tag plans_path, { method: :get, class: "form form-inline", role: "search"} do %>
  <div class="form-group">
    <%= label_tag :q, "Search term", {class: "sr-only"} %>
    <%= text_field_tag :q, @q, {placeholder: "Name", class: "form-control"} %>
    <%= submit_tag "Search", { class: "btn btn-primary" } %>
  </div>
<% end %>

app/views/plans/_plans_list.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
    	<th>Name</th>
      <th>Coverage Type</th>
      <th>Metal level</th>
    </tr>
  </thead>
  <tbody>
    <%= table_empty_to_human if plans.count < 1 %>
    <% plans.each do |p| %>
      <tr>
        <td><%= link_to p.name, plan_path(p.id) %></td>
        <td><%= p.coverage_type.capitalize %></td>
        <td><%= p.metal_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plans/calculate_premium.js.erb
<%- if @rate %>
	$('#rate-result').text("Result: $" + parseFloat( "<%= escape_javascript(@rate.amount.to_s) %>" ).toFixed( 2 );
<%- else %>
	$('#rate-result').text("Premium Not Found")
<%- end %>

app/views/plans/index.html.erb
<div class="page-header">
  <%= render 'shared/breadcrumb', crumbs: ['Plans'] %>

  <div class="row">
    <div class="col-md-8">
      <%#= link_to "New", new_plan_path, class: "btn btn-primary" %>
    </div>
    <div class="col-md-4">
      <%= render 'plan_search', q: @q %>
    </div>
  </div>
</div>
<%= render "plans_list", plans: @plans %>
<div class="row">
  <div class="col-md-8">
    <%= paginate @plans, theme: "twitter-bootstrap", pagination_class: "pagination-plain" %>
  </div>
  <div class="rol-md-4">
    <p><%= "#{number_with_delimiter(@plans.count)} / #{number_with_delimiter(Plan.count)} " %><small>(plans selected / total)</small></p>
  </div>
</div>

app/views/plans/show.html.erb
<div class="page-header">
  <%t '.title', :default => Plan.model_name.human.titleize.pluralize %>
  <%= render 'shared/breadcrumb', crumbs: [
      link_to('Plans', plans_path),
      @plan.name
    ] 
  %>
</div>

<div class='col-md-offset-2 col-md-10'>
  <h4><%= @plan.name %></h4>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="fui-tag">&nbsp;</span>
        Calculate Premium
      </h3>
    </div>

    <div class="panel-body">

      <%= form_tag calculate_premium_plan_path(@plan.id), method: :get, remote: true, class: 'form-horizontal' do %>
        <div class="form-group">

          <div class="row">
            <div class="col-md-2 text-center">
              <%= label_tag :rate_period_date %>
            </div>
            <div class="col-md-3">
              <%= text_field_tag :rate_period_date, @rate_period_date, { class: 'date_picker'} %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-2 text-center">
              <%= label_tag :benefit_begin_date %>
            </div>
            <div class="col-md-3">
              <%= text_field_tag :benefit_begin_date, @benefit_begin_date, { class: 'date_picker'} %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-2 text-center">
              <%= label_tag :birth_date %>
            </div>
            <div class="col-md-3">
              <%= text_field_tag :birth_date, @birth_date, { class: 'date_picker' } %>
            </div>
          </div>

          <div class="col-md-offset-1 col-md-2 text-center">
            <%= submit_tag "Calculate", { :class => "btn btn-primary" } %>
          </div>
        </div>
      <% end %>

      <h5 id='rate-result'>Result: $0.00</h5>

    </div>
  </div>

</div>