config/routes.rb
Gluedb::Application.routes.draw do

  devise_for :users, :path => "accounts"

  root :to => 'dashboards#index'

  get "dashboards/index"
  get "welcome/index"
  get "tools/premium_calc"
  get "flatuipro_demo/index"

  namespace :admin do
    namespace :settings do
      resources :hbx_policies
    end
    resources :users
  end

  resources :enrollment_addresses

  resources :plan_metrics, :only => :index

  resources :vocab_uploads, :only => [:new, :create]

  resources :enrollment_transmission_updates, :only => :create

  resources(:change_vocabularies, :only => [:new, :create]) do
    collection do
      get 'download'
    end
  end

  resources :edi_transaction_set_payments
  resources :edi_transaction_sets
  resources :edi_transmissions

  resources :enrollments do
    member do
      get :canonical_vocabulary
    end
  end

  resources :application_groups do
    resources :households
    get 'page/:page', :action => :index, :on => :collection
  end
    
  resources :users
  resources :policies

  resources :individuals 
  resources :people do
    get 'page/:page', :action => :index, :on => :collection
    member do
      put :compare
      put :persist_and_transmit
      put :assign_authority_id
    end
  end

  resources :employers do
    get 'page/:page', action: :index, :on => :collection
    member do
      get :group
    end
    resources :employees, except: [:destroy], on: :member do
      member do
        put :compare
        put :terminate
      end
    end
  end

  resources :brokers do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :carriers do
    resources :plans
    get :show_plans
    post :calculate_premium, on: :collection  
  end

  resources :plans, only: [:index, :show] do
    member do
      get :calculate_premium
    end
  end

  resources :policies, only: [:show]

end

app/models/household.rb
class Household
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Paranoia


#  field :rel, as: :relationship, type: String
  field :active, type: Boolean, default: true   # Household active on the Exchange?
  field :relationships, type: Array, default: []
  field :notes, type: String

#  validates :rel, presence: true, inclusion: {in: %w( subscriber responsible_party spouse life_partner child ward )}

  belongs_to :application_group, counter_cache: true
  has_many :people
  has_and_belongs_to_many :policies, inverse_of: nil

  embeds_many :person_relationships
  accepts_nested_attributes_for :person_relationships, reject_if: proc { |attribs| attribs['subject_person', 'relationship_kind', 'object_person'].blank? }, allow_destroy: true

  embeds_many :eligibilities
  accepts_nested_attributes_for :eligibilities, reject_if: proc { |attribs| attribs['date_determined'].blank? }, allow_destroy: true

  def self.create_for_people(the_people)
    found = self.where({
      "person_ids" => { 
        "$all" => the_people.map(&:id),
        "$size" => the_people.length
       }
    }).first
    return(nil) if found
    self.create!( :people => the_people )
  end

  def current_eligibility
    eligibilities.max_by { |e| e.date_determined }
  end

  # Value from latest eligibility determination
  def max_aptc
    current_eligibility.max_aptc
  end

  # Value from latest eligibility determination
  def csr_percent
    current_eligibility.csr_percent
  end

  def subscriber
    #TODO - correct when household has policy association
    people.detect do |person|
      person.members.detect do |member|
        member.enrollees.detect(&:subscriber?) 
      end
    end
  end

end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  def index
    @q = params[:q]
    @qf = params[:qf]
    @qd = params[:qd]

    if params[:q].present?
      @households = Household.search(@q, @qf, @qd).page(params[:page]).per(15)
    else
      @households = Household.page(params[:page]).per(15)
    end


    respond_to do |format|
	    format.html # index.html.erb
	    format.json { render json: @households }
	  end
  end

  def show
		@household = Household.find(params[:id])

	  respond_to do |format|
		  format.html # index.html.erb
		  format.json { render json: @household }
		end
  end

  def new
    @household = Household.new
    build_nested_models

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @household }
    end
  end

  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        format.html { redirect_to @household, notice: 'Household was successfully created.' }
        format.json { render json: @household, status: :created, location: @household }
      else
        format.html { render action: "new" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @household = Household.find(params[:id])
    build_nested_models
  end

  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to @household, notice: 'Household was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def build_nested_models
    @household.people.build if @household.people.empty?
    @household.special_enrollment_periods.build if @household.special_enrollment_periods.empty?
    @household.eligibilities.build if @household.eligibilities.empty?
  end


end

app/helpers/households_helper.rb
	module HouseholdsHelper
		def controls_for_households(household)
			# TODO: add roles/filters
			# if current_user.manages?(person)
			if user_signed_in?
				partial = controls_partial_for_households(household)
				contents = render(partial: partial, locals: {household: household})
				content_tag(:ul, contents, class: "nav nav-list")
			end
		end

		def controls_partial_for_people(household)
			'housholds/controls/admin'
			# if current_user.admin?
			# 	'people/controls/admin'
			# elsif current_user.author?
			# 	'people/controls/author'
			# elsif current_user.editor?
			# 	'people/controls/editor'
			# end
		end
end

app/views/households/_admin.html.erb
<li class="nav-header">Individual</li>
<% if @person.can_edit_family_address? %>
  <li><%= link_to "Change Address", edit_enrollment_address_path(@person, {:id => @person._id}) %></li>
<% end %>
<li><a href="#">Set Authority</a></li>
<li><%= link_to "Edit", edit_person_path(@person) %>
<li><%= link_to "Add Dependent", new_person_path %>
<li><%= link_to "Drop Dependent", new_person_path %>
<li class="nav-header">Coverage</li>
<li><a href="#">New Policy</a></li>
<li><a href="#">Change Carrier</a></li>
<li><a href="#">Change Plan</a></li>
<li><a href="#">Cancel/Term</a></li>
<li class="nav-header">Tasks</li>
<li><a href="#">Transmit Changes</a></li>
<li><a href="#">Special Enrollment Period</a></li>

app/views/households/_author.html.erb
<li class="nav-header">Edit</li>
<% if @person.can_edit_family_address? %>
  <li><%= link_to "Change Address", edit_enrollment_address_path(@person, {:id => @person._id}) %></li>
<% end %>
<li><a href="#">Set Authority Member</a></li>
<li><%= link_to "Change Member Info", edit_person_path(@person) %>
<li><%= link_to "Add Dependent", new_person_path %>
<li class="nav-header">Enrollment</li>
<li><a href="#">Special Enrollment Period</a></li>
<li><a href="#">Enroll in Plan</a></li>
<li><a href="#">Change Carrier</a></li>
<li><a href="#">Change Plan</a></li>
<li><a href="#">Cancel/Term Plan</a></li>
<li><a href="#">Transmit Changes</a></li>

app/views/households/_editor.html.erb
<li class="nav-header">Edit</li>
<% if @person.can_edit_family_address? %>
  <li><%= link_to "Change Address", edit_enrollment_address_path(@person, {:id => @person._id}) %></li>
<% end %>
<li><a href="#">Set Authority Member</a></li>
<li><%= link_to "Change Member Info", edit_person_path(@person) %>
<li><%= link_to "Add Dependent", new_person_path %>
<li class="nav-header">Enrollment</li>
<li><a href="#">Special Enrollment Period</a></li>
<li><a href="#">Enroll in Plan</a></li>
<li><a href="#">Change Carrier</a></li>
<li><a href="#">Change Plan</a></li>
<li><a href="#">Cancel/Term Plan</a></li>
<li><a href="#">Transmit Changes</a></li>

app/views/households/_eligibility_detail.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Determination Date</th>
      <th>Maximum APTC</th>
      <th>CSR Pct</th>
    </tr>
  </thead>
  <tbody>
		<% eligibilities.each do |e| %>
		  <tr>
		    <td><%= format_date(e.date_determined) %></td>
		    <td><%= number_to_currency(e.max_aptc) %></td>
		    <td><%= number_to_percentage(e.csr_percent) %></td>
		  </tr>
		<% end %>
  </tbody>
</table>

app/views/households/_eligibility_fields.html.erb
<fieldset>
  <div class="row">
    <div>
      <div class="col-md-3">
        <div class="input-group">
          <span class="input-group-btn">
            <button class="btn" type="button"><span class="fui-calendar"></span></button>
          </span>
          <%= f.input_field :date_determined, as: :string,
            start_year: Date.today.year - 1, 
            end_year: Date.today.year + 1, 
            placeholder: "mm/dd/yyyy",
            class: "date_picker",
            value: f.object.date_determined.try(:strftime, "%m/%d/%Y") %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <%= f.input_field :max_aptc, as: :string, title: "APTC", placeholder: "APTC", input_html: { value: number_to_currency(f.object.max_aptc), maxlength: 11 } %>
    </div>
    <div class="col-md-2">
      <%= f.input_field :csr_percent, as: :string, title: "CSR", placeholder: "CSR", input_html: { value: number_to_percentage(f.object.csr_percent), maxlength: 11 } %>
    </div>
    <div class="col-md-3">
      <%= link_to '<span class="fui-cross-inverted"> Delete</span>'.html_safe, '#', :class => "remove_fields btn btn-small btn-danger" %>
    </div>
  </div>
  <%= f.hidden_field :_destroy %>
</fieldset>

app/views/households/_form.html.erb
<%= simple_form_for @household, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.error_notification %>
    <% if @household.errors.any? %>
    <div class="alert alert-error">
      <h4><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h4>
      <ul>
      <% @household.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

      <% @household.embedded_error_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <!-- <div class="col-md-offset-1 col-md-3"> -->
      <%#= f.input :rel, as: :select, collection: ["self", "spouse", "child", "life partner"], include_blank: "Relationship" %>
    <!-- </div> -->
  </div>

  <legend>People</legend>
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="form-inputs">
        <%= f.simple_fields_for :people do |p|  %>
          <%#= render 'sep_fields', p: p %>
        <% end %>
      </div>
    </div>
  </div>

  <legend>Special Enrollment Periods</legend>
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="form-inputs">
        <%= f.simple_fields_for :special_enrollment_periods do |s|  %>
          <%= render 'special_enrollment_period_fields', f: s %>
        <% end %>
        <%= link_to_add_fields "Add Special Enrollment Period", f, :special_enrollment_periods %>
      </div>
    </div>
  </div>

  <legend>Eligibility Determinations</legend>
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="form-inputs">
        <%= f.simple_fields_for :eligibilities do |e|  %>
          <%= render 'eligibility_fields', f: e %>
        <% end %>
        <%= link_to_add_fields "Add Enligibility", f, :eligibilities %>
      </div>
    </div>
  </div>

  <div class="well well-sm well-default">
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), households_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/households/_households_list.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Subscriber Name</th>
      <th># Individuals</th>
      <th># SEPs</th>
      <th># Eligibilities</th>
    </tr>
  </thead>
  <tbody>
    <%= table_empty_to_human if households.count < 1 %>
    <% households.each do |h| %>
      <tr>
        <td>
          <%= link_to prepend_glyph_to_name(h.subscriber.full_name), household_path(h) %>
        </td>
        <td><%= h.people.count %></td>
        <td><%= h.special_enrollment_periods.count %></td>
        <td><%= h.eligibilities.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/households/_sep_detail.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Reason</th>
      <th>Start Date</th>
      <th>End Date</th>
    </tr>
  </thead>
  <tbody>
		<% seps.each do |sep| %>
		  <tr>
		    <td><%= sep.reason.capitalize %></td>
		    <td><%= format_date(sep.start_date) %></td>
		    <td><%= format_date(sep.end_date) %></td>
		  </tr>
		<% end %>
  </tbody>
</table>

app/views/households/_sep_fields.html.erb
<fieldset>
  <div class="row">
    <div class="col-md-3">
      <%= s.input :reason, as: :select, collection: ["birth", "death", "adoption"], include_blank: "SEP Reason" %>
    </div>
    <div class="col-md-4">
      <div class="input-group col-sm-4">
        <span class="input-group-btn">
          <button class="btn" type="button"><span class="fui-calendar"></span></button>
        </span>
        <%= s.input_field :start_date, as: :string,
          start_year: Date.today.year - 1, 
          end_year: Date.today.year + 1, 
          placeholder: "mm/dd/yyyy",
          class: "date_picker",
          value: s.object.start_date.try(:strftime, "%m/%d/%Y")
        %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="input-group col-sm-4">
        <span class="input-group-btn">
          <button class="btn" type="button"><span class="fui-calendar"></span></button>
        </span>
        <%= s.input_field :end_date, as: :string,
          start_year: Date.today.year - 1, 
          end_year: Date.today.year + 1, 
          placeholder: "mm/dd/yyyy",
          class: "date_picker",
          value: s.object.end_date.try(:strftime, "%m/%d/%Y")
        %>
      </div>
    </div>
  </div>
</fieldset>

app/views/households/_special_enrollment_period_fields.html.erb
<fieldset>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :reason, as: :select, collection: ["birth", "death", "adoption"], include_blank: "SEP Reason" %>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-btn">
          <button class="btn" type="button"><span class="fui-calendar"></span></button>
        </span>
        <%= f.input_field :start_date, as: :string,
          start_year: Date.today.year - 1, 
          end_year: Date.today.year + 1, 
          placeholder: "mm/dd/yyyy",
          class: "date_picker",
          value: f.object.start_date.try(:strftime, "%m/%d/%Y")
        %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="input-group">
        <span class="input-group-btn">
          <button class="btn" type="button"><span class="fui-calendar"></span></button>
        </span>
        <%= f.input_field :end_date, as: :string,
          start_year: Date.today.year - 1, 
          end_year: Date.today.year + 1, 
          placeholder: "mm/dd/yyyy",
          class: "date_picker",
          value: f.object.end_date.try(:strftime, "%m/%d/%Y")
        %>
      </div>
    </div>
    <div class="col-md-3">
      <%= link_to '<span class="fui-cross-inverted"> Delete</span>'.html_safe, '#', :class => "remove_fields btn btn-small btn-danger" %>
    </div>
  </div>
  <%= f.hidden_field :_destroy %>
</fieldset>

app/views/households/index.html.erb
<%- model_class = Household -%>
<%t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<div class="page-header">
  <%= render 'shared/breadcrumb', crumbs: ['Households'] %>

  <div class="row">
    <div class="col-md-8">
      <%= link_to "New", new_household_path, class: "btn btn-primary" %>
    </div>
    <div class="col-md-4">
      <%#= render 'people/person_search', q: @q %>
    </div>
  </div>
</div>

<%= render "households_list", households: @households %>

<div class="row">
  <div class="col-md-8">
    <%= paginate @households, theme: "twitter-bootstrap", pagination_class: "pagination-plain" %>
  </div>
  <div class="rol-md-4">
    <p><%= "#{number_with_delimiter(@households.count)} / #{number_with_delimiter(Household.count)} " %><small>(households selected / total)</small></p>
  </div>
</div>

app/views/households/new.html.erb
<%- model_class = Household -%>
<div class="page-header">
  <%= render 'shared/breadcrumb', crumbs: [
      link_to('Households', households_path),
      'New'
    ] 
  %>
</div>
<%= render :partial => 'form' %>

app/views/households/show.html.erb
<%- model_class = Household -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  <%= render 'shared/breadcrumb', crumbs: [
      link_to('Households', households_path),
      @household.subscriber.full_name
    ] 
  %>
</div>

<div class="row">
  <div class="col-md-2">
    <div class="well sidebar-nav">
      <ul class="nav nav-list">
        <li class="nav-header">Individual</li>
        <li><%= link_to "Edit", edit_household_path(@household) %></li>
      </ul>
    </div>
  </div>

  <div class="col-md-10">
    <h4>Household Members</h4>
    <% @household.people.each do |person| %>
      <%= link_to prepend_glyph_to_name(person.full_name), person_path(person) %>
      <br/> 
  <!--     <dl class="dl-horizontal">
        <dt><%#= "Person name" %></dt>
        <dd><%#= "Person" %></dd>
      </dl> -->
    <% end %>

    <h4>Special Enrollment Periods</h4>
    <%= render 'sep_detail', seps: @household.special_enrollment_periods %>

    <h4>Eligibility Determinations</h4>
    <%= render 'eligibility_detail', eligibilities: @household.eligibilities %>

  </div>
</div>

  <p class="text-right">
    <small><%= version_for_record(@household) %></small>
  </p>

<div class="well well-sm well-default">
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")), households_path, :class => 'btn btn-primary'  %>
  </div>
</div>